[package]
name = "loopflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "loopflow"
crate-type = ["cdylib"]

[dependencies]
loopflow-engine = { path = "../loopflow-engine" }
loopflow-ops = { path = "../loopflow-ops" }
pyo3 = { version = "0.21", features = ["extension-module"] }
