//! Built-in step definitions and system docs embedded in the binary.
//!
//! Registration is automatic: drop a file into the right builtins/
//! subdirectory and build.rs generates the HashMap entries.

/// Bundled LOOPFLOW.md system documentation.
pub const LOOPFLOW_DOC: &str = include_str!("builtins/LOOPFLOW.md");

/// Bundled RLM.md — recursive language model instructions for agents.
pub const RLM_DOC: &str = include_str!("builtins/RLM.md");

/// Returns the content of a built-in step, if it exists.
///
/// Namespaced steps (e.g., "scan/scan-report") are registered with their prefix.
/// The auto-registration in build.rs uses file stems as keys, so namespaced
/// steps need explicit overrides here.
pub fn get_builtin_step(name: &str) -> Option<&'static str> {
    BUILTIN_STEPS
        .get(name)
        .copied()
        .or_else(|| NAMESPACED_STEPS.get(name).copied())
}

/// Steps whose key includes a directory prefix (e.g., "scan/scan-report").
/// build.rs auto-registers these under their file stem ("scan-report"), but
/// the user-facing name includes the namespace.
static NAMESPACED_STEPS: std::sync::LazyLock<
    std::collections::HashMap<&'static str, &'static str>,
> = std::sync::LazyLock::new(|| {
    let mut m = std::collections::HashMap::new();
    m.insert(
        "scan/scan-report",
        include_str!("builtins/steps/scan/scan-report.md"),
    );
    m.insert(
        "scan/scan-plan",
        include_str!("builtins/steps/scan/scan-plan.md"),
    );
    m
});

/// Returns the content of a built-in flow, if it exists.
pub fn get_builtin_flow(name: &str) -> Option<&'static str> {
    BUILTIN_FLOWS.get(name).copied()
}

/// Returns the content of a built-in direction, if it exists.
pub fn get_builtin_direction(name: &str) -> Option<&'static str> {
    BUILTIN_DIRECTIONS.get(name).copied()
}

/// Returns the content of a built-in ops prompt, if it exists.
pub fn get_builtin_ops_prompt(name: &str) -> Option<&'static str> {
    BUILTIN_OPS_PROMPTS.get(name).copied()
}

/// List of all built-in step names.
pub fn builtin_step_names() -> Vec<&'static str> {
    let mut names: Vec<_> = BUILTIN_STEPS.keys().copied().collect();
    names.extend(NAMESPACED_STEPS.keys().copied());
    names
}

/// List of all built-in flow names.
pub fn builtin_flow_names() -> Vec<&'static str> {
    BUILTIN_FLOWS.keys().copied().collect()
}

/// Iterate over all built-in flows as (name, yaml_content) pairs.
pub fn builtin_flow_entries() -> impl Iterator<Item = (&'static str, &'static str)> {
    BUILTIN_FLOWS.iter().map(|(k, v)| (*k, *v))
}

/// List of all built-in direction names.
pub fn builtin_direction_names() -> Vec<&'static str> {
    BUILTIN_DIRECTIONS.keys().copied().collect()
}

/// Return direction members for a built-in group name.
pub fn get_builtin_direction_group(name: &str) -> Option<&'static [&'static str]> {
    BUILTIN_DIRECTION_GROUPS
        .iter()
        .find_map(|(group, members)| (*group == name).then_some(*members))
}

/// List of all built-in direction group names.
pub fn builtin_direction_group_names() -> Vec<&'static str> {
    BUILTIN_DIRECTION_GROUPS
        .iter()
        .map(|(name, _)| *name)
        .collect()
}

const BUILTIN_DIRECTION_GROUPS: [(&str, &[&str]); 2] = [
    (
        "roles",
        &["ceo", "designer", "infra-engineer", "product-engineer"],
    ),
    ("values", &["craft", "flow", "scale"]),
];

// Generated by build.rs — scans builtins/ subdirectories automatically.
include!(concat!(env!("OUT_DIR"), "/builtin_steps.rs"));
include!(concat!(env!("OUT_DIR"), "/builtin_flows.rs"));
include!(concat!(env!("OUT_DIR"), "/builtin_flow_categories.rs"));
include!(concat!(env!("OUT_DIR"), "/builtin_directions.rs"));
include!(concat!(env!("OUT_DIR"), "/builtin_ops_prompts.rs"));
