exclude:
  - uv.lock

branch_names:
  schema: "{user}.{name}.{ts}"

pm:
  provider: asana

asana:
  team: "1214267955480461"  # Loopflow team — Desktop, Root, Mobile, Workflows

internal:
  use_rust: true
