use crate::engine::{Step, XorPath};
use std::collections::HashMap;
use std::path::Path;

pub use crate::engine::builtins::{builtin_skill_description, BUILTIN_SKILL_CATEGORIES};
use crate::engine::target::Target;

pub(crate) fn definition_source(repo: &Path, path: Option<&Path>) -> String {
    path.map(|path| {
        path.strip_prefix(repo)
            .unwrap_or(path)
            .display()
            .to_string()
    })
    .unwrap_or_else(|| "builtin".to_string())
}

// =============================================================================
// Built-in flow metadata for formatted listing
// =============================================================================

// Generated by build.rs from the flows/ directory structure.
pub use crate::engine::builtins::BUILTIN_FLOW_CATEGORIES;

pub fn format_written_steps(steps: &[Step]) -> String {
    if steps.is_empty() {
        return "∅".to_string();
    }
    steps
        .iter()
        .map(format_written_step)
        .collect::<Vec<_>>()
        .join(" → ")
}

fn format_written_step(step: &Step) -> String {
    match &step.target {
        Target::Flow(flow) => flow.name.clone(),
        target => format_target(target),
    }
}

pub(crate) fn format_target(target: &Target) -> String {
    match target {
        Target::Skill(skill) => skill.name.clone(),
        Target::Command(command) => command.to_string(),
        Target::Flow(flow) => format_written_steps(&flow.items),
        Target::Xor(xor) => format_xor(xor.router.as_deref(), &xor.paths),
    }
}

fn format_xor(router: Option<&str>, paths: &HashMap<String, XorPath>) -> String {
    let label = router.map_or_else(|| "xor".to_string(), |name| format!("xor[{name}]"));
    let mut names: Vec<_> = paths.keys().collect();
    names.sort();
    let rendered = names
        .into_iter()
        .map(|name| format!("{name}: {}", format_written_steps(&paths[name].steps)))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("{label}{{{rendered}}}")
}

#[cfg(test)]
mod tests {
    use crate::engine::target::{resolve_definition, DefinitionKind, Target};
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn ordinary_skill_discovery_ignores_legacy_review_instructions() {
        let _lock = crate::journal::test_env_lock();
        let _environment = crate::test_ambient::EnvGuard::clear(&["LF_HUMAN_SESSION"]);
        let repo = TempDir::new().unwrap();
        fs::create_dir_all(repo.path().join(".lf/skills")).unwrap();
        fs::write(
            repo.path().join(".lf/skills/review.md"),
            "Current instructions",
        )
        .unwrap();
        let mut captured = crate::engine::Skill::named("review");
        captured.content = Some("Retired captured instructions".into());
        std::env::set_var(
            "LF_HUMAN_SESSION",
            serde_json::json!({
                "kind": "flow",
                "token": {
                    "task_id": crate::work::task::TaskId::new(),
                    "invocation_id": "legacy",
                    "flow": "legacy",
                    "node_id": "review",
                    "skill": captured,
                    "iteration": 0
                }
            })
            .to_string(),
        );

        let Target::Skill(skill) =
            resolve_definition(repo.path(), "review", Some(DefinitionKind::Skill)).unwrap()
        else {
            panic!("explicit skill must resolve to a skill");
        };
        assert_eq!(skill.content.as_deref(), Some("Current instructions"));
    }

    #[test]
    fn operate_resolves_to_repo_and_wave_operate_stays_explicit() {
        let tmp = TempDir::new().unwrap();
        for (name, expected) in [
            ("operate", "repo/operate"),
            ("repo/operate", "repo/operate"),
            ("wave/operate", "wave/operate"),
        ] {
            let Target::Skill(skill) = resolve_definition(tmp.path(), name, None).unwrap() else {
                panic!("expected a skill for {name}");
            };
            assert_eq!(skill.name, expected);
        }

        let skills = tmp.path().join(".lf/skills/repo");
        fs::create_dir_all(&skills).unwrap();
        fs::write(skills.join("operate.md"), "Repository operation override").unwrap();
        for name in ["operate", "repo/operate"] {
            let Target::Skill(skill) = resolve_definition(tmp.path(), name, None).unwrap() else {
                panic!("expected a skill for {name}");
            };
            assert_eq!(skill.name, "repo/operate");
            assert_eq!(
                skill.content.as_deref(),
                Some("Repository operation override")
            );
        }
    }

    #[test]
    fn untyped_names_resolve_available_definitions() {
        let tmp = TempDir::new().expect("tempdir");
        for name in ["design", "launch-plan", "debug", "unbreak", "implement"] {
            assert!(
                matches!(
                    resolve_definition(tmp.path(), name, None).unwrap(),
                    Target::Skill(_)
                ),
                "{name}"
            );
        }
        for name in ["pursue", "incident", "vsm-operate"] {
            assert!(
                matches!(
                    resolve_definition(tmp.path(), name, None).unwrap(),
                    Target::Flow(_)
                ),
                "{name}"
            );
        }
        // A workflow is traversed by `lf task run`, never run as a Flow.
        for name in ["feature", "code"] {
            let error = resolve_definition(tmp.path(), name, None).unwrap_err();
            assert!(matches!(error, crate::engine::LoadError::Workflow(_)));
        }
    }
}
