# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from loopflow.proto.loopflow.control.v1 import (
    control_pb2 as loopflow_dot_control_dot_v1_dot_control__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in loopflow/control/v1/control_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ControlServiceStub(object):
    """-----------------------------------------------------------------------------
    Service Definitions
    -----------------------------------------------------------------------------

    ControlService provides wave management and daemon control.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetStatus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetHealth = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetHealth",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthResponse.FromString,
            _registered_method=True,
        )
        self.ListWaves = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListWaves",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesResponse.FromString,
            _registered_method=True,
        )
        self.GetWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveResponse.FromString,
            _registered_method=True,
        )
        self.CreateWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/CreateWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveResponse.FromString,
            _registered_method=True,
        )
        self.UpdateWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/UpdateWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveResponse.FromString,
            _registered_method=True,
        )
        self.DeleteWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/DeleteWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveResponse.FromString,
            _registered_method=True,
        )
        self.CloneWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/CloneWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveResponse.FromString,
            _registered_method=True,
        )
        self.ListWaveRuns = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListWaveRuns",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsResponse.FromString,
            _registered_method=True,
        )
        self.GetWaveRun = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetWaveRun",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunResponse.FromString,
            _registered_method=True,
        )
        self.RunWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/RunWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveResponse.FromString,
            _registered_method=True,
        )
        self.StopWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/StopWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveResponse.FromString,
            _registered_method=True,
        )
        self.ConnectWave = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ConnectWave",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveResponse.FromString,
            _registered_method=True,
        )
        self.ListFlows = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListFlows",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsResponse.FromString,
            _registered_method=True,
        )
        self.ListWorktrees = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListWorktrees",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesResponse.FromString,
            _registered_method=True,
        )
        self.NotifyWorktreeChanged = channel.unary_unary(
            "/loopflow.control.v1.ControlService/NotifyWorktreeChanged",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedResponse.FromString,
            _registered_method=True,
        )
        self.GetSchedulerStatus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetSchedulerStatus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusResponse.FromString,
            _registered_method=True,
        )
        self.AcquireSlot = channel.unary_unary(
            "/loopflow.control.v1.ControlService/AcquireSlot",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotResponse.FromString,
            _registered_method=True,
        )
        self.ReleaseSlot = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ReleaseSlot",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotResponse.FromString,
            _registered_method=True,
        )
        self.ListStimuli = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListStimuli",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliResponse.FromString,
            _registered_method=True,
        )
        self.GetStimulus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetStimulus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusResponse.FromString,
            _registered_method=True,
        )
        self.CreateStimulus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/CreateStimulus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusResponse.FromString,
            _registered_method=True,
        )
        self.UpdateStimulus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/UpdateStimulus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusResponse.FromString,
            _registered_method=True,
        )
        self.DeleteStimulus = channel.unary_unary(
            "/loopflow.control.v1.ControlService/DeleteStimulus",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusResponse.FromString,
            _registered_method=True,
        )
        self.ListAgents = channel.unary_unary(
            "/loopflow.control.v1.ControlService/ListAgents",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.FromString,
            _registered_method=True,
        )
        self.GetAgentHistory = channel.unary_unary(
            "/loopflow.control.v1.ControlService/GetAgentHistory",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryResponse.FromString,
            _registered_method=True,
        )
        self.StartAgent = channel.unary_unary(
            "/loopflow.control.v1.ControlService/StartAgent",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentResponse.FromString,
            _registered_method=True,
        )
        self.EndAgent = channel.unary_unary(
            "/loopflow.control.v1.ControlService/EndAgent",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentResponse.FromString,
            _registered_method=True,
        )
        self.Subscribe = channel.unary_stream(
            "/loopflow.control.v1.ControlService/Subscribe",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.Event.FromString,
            _registered_method=True,
        )
        self.Notify = channel.unary_unary(
            "/loopflow.control.v1.ControlService/Notify",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyResponse.FromString,
            _registered_method=True,
        )
        self.StreamOutput = channel.unary_stream(
            "/loopflow.control.v1.ControlService/StreamOutput",
            request_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputRequest.SerializeToString,
            response_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputResponse.FromString,
            _registered_method=True,
        )


class ControlServiceServicer(object):
    """-----------------------------------------------------------------------------
    Service Definitions
    -----------------------------------------------------------------------------

    ControlService provides wave management and daemon control.
    """

    def GetStatus(self, request, context):
        """Health and status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListWaves(self, request, context):
        """Wave management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloneWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListWaveRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWaveRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunWave(self, request, context):
        """Wave control"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopWave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConnectWave(self, request, context):
        """Session connect (interactive steps)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListFlows(self, request, context):
        """Flow discovery"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListWorktrees(self, request, context):
        """Worktree management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def NotifyWorktreeChanged(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchedulerStatus(self, request, context):
        """Scheduler"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AcquireSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReleaseSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListStimuli(self, request, context):
        """Stimulus management (triggers for waves)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStimulus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateStimulus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateStimulus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteStimulus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListAgents(self, request, context):
        """Agent management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAgentHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EndAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """Event streaming"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Notify(self, request, context):
        """Notifications (fire-and-forget from external systems)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusResponse.SerializeToString,
        ),
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthResponse.SerializeToString,
        ),
        "ListWaves": grpc.unary_unary_rpc_method_handler(
            servicer.ListWaves,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesResponse.SerializeToString,
        ),
        "GetWave": grpc.unary_unary_rpc_method_handler(
            servicer.GetWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveResponse.SerializeToString,
        ),
        "CreateWave": grpc.unary_unary_rpc_method_handler(
            servicer.CreateWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveResponse.SerializeToString,
        ),
        "UpdateWave": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveResponse.SerializeToString,
        ),
        "DeleteWave": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveResponse.SerializeToString,
        ),
        "CloneWave": grpc.unary_unary_rpc_method_handler(
            servicer.CloneWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveResponse.SerializeToString,
        ),
        "ListWaveRuns": grpc.unary_unary_rpc_method_handler(
            servicer.ListWaveRuns,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsResponse.SerializeToString,
        ),
        "GetWaveRun": grpc.unary_unary_rpc_method_handler(
            servicer.GetWaveRun,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunResponse.SerializeToString,
        ),
        "RunWave": grpc.unary_unary_rpc_method_handler(
            servicer.RunWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveResponse.SerializeToString,
        ),
        "StopWave": grpc.unary_unary_rpc_method_handler(
            servicer.StopWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveResponse.SerializeToString,
        ),
        "ConnectWave": grpc.unary_unary_rpc_method_handler(
            servicer.ConnectWave,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveResponse.SerializeToString,
        ),
        "ListFlows": grpc.unary_unary_rpc_method_handler(
            servicer.ListFlows,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsResponse.SerializeToString,
        ),
        "ListWorktrees": grpc.unary_unary_rpc_method_handler(
            servicer.ListWorktrees,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesResponse.SerializeToString,
        ),
        "NotifyWorktreeChanged": grpc.unary_unary_rpc_method_handler(
            servicer.NotifyWorktreeChanged,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedResponse.SerializeToString,
        ),
        "GetSchedulerStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchedulerStatus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusResponse.SerializeToString,
        ),
        "AcquireSlot": grpc.unary_unary_rpc_method_handler(
            servicer.AcquireSlot,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotResponse.SerializeToString,
        ),
        "ReleaseSlot": grpc.unary_unary_rpc_method_handler(
            servicer.ReleaseSlot,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotResponse.SerializeToString,
        ),
        "ListStimuli": grpc.unary_unary_rpc_method_handler(
            servicer.ListStimuli,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliResponse.SerializeToString,
        ),
        "GetStimulus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStimulus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusResponse.SerializeToString,
        ),
        "CreateStimulus": grpc.unary_unary_rpc_method_handler(
            servicer.CreateStimulus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusResponse.SerializeToString,
        ),
        "UpdateStimulus": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateStimulus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusResponse.SerializeToString,
        ),
        "DeleteStimulus": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteStimulus,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusResponse.SerializeToString,
        ),
        "ListAgents": grpc.unary_unary_rpc_method_handler(
            servicer.ListAgents,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.SerializeToString,
        ),
        "GetAgentHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetAgentHistory,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryResponse.SerializeToString,
        ),
        "StartAgent": grpc.unary_unary_rpc_method_handler(
            servicer.StartAgent,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentResponse.SerializeToString,
        ),
        "EndAgent": grpc.unary_unary_rpc_method_handler(
            servicer.EndAgent,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentResponse.SerializeToString,
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.SubscribeRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.Event.SerializeToString,
        ),
        "Notify": grpc.unary_unary_rpc_method_handler(
            servicer.Notify,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.NotifyResponse.SerializeToString,
        ),
        "StreamOutput": grpc.unary_stream_rpc_method_handler(
            servicer.StreamOutput,
            request_deserializer=loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputRequest.FromString,
            response_serializer=loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "loopflow.control.v1.ControlService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("loopflow.control.v1.ControlService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """-----------------------------------------------------------------------------
    Service Definitions
    -----------------------------------------------------------------------------

    ControlService provides wave management and daemon control.
    """

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetStatus",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetHealth",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListWaves(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListWaves",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWavesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/CreateWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.CreateWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/UpdateWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.UpdateWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/DeleteWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.DeleteWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloneWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/CloneWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.CloneWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListWaveRuns(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListWaveRuns",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWaveRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetWaveRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetWaveRun",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetWaveRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/RunWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.RunWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/StopWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.StopWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConnectWave(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ConnectWave",
            loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ConnectWaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListFlows(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListFlows",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListWorktrees(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListWorktrees",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListWorktreesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NotifyWorktreeChanged(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/NotifyWorktreeChanged",
            loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.NotifyWorktreeChangedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSchedulerStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetSchedulerStatus",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetSchedulerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AcquireSlot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/AcquireSlot",
            loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.AcquireSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReleaseSlot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ReleaseSlot",
            loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ReleaseSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListStimuli(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListStimuli",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListStimuliResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStimulus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetStimulus",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetStimulusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateStimulus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/CreateStimulus",
            loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.CreateStimulusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateStimulus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/UpdateStimulus",
            loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.UpdateStimulusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteStimulus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/DeleteStimulus",
            loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.DeleteStimulusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListAgents(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/ListAgents",
            loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAgentHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/GetAgentHistory",
            loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.GetAgentHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/StartAgent",
            loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.StartAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EndAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/EndAgent",
            loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.EndAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/loopflow.control.v1.ControlService/Subscribe",
            loopflow_dot_control_dot_v1_dot_control__pb2.SubscribeRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Notify(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/loopflow.control.v1.ControlService/Notify",
            loopflow_dot_control_dot_v1_dot_control__pb2.NotifyRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.NotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamOutput(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/loopflow.control.v1.ControlService/StreamOutput",
            loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputRequest.SerializeToString,
            loopflow_dot_control_dot_v1_dot_control__pb2.StreamOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
