#!/usr/bin/env python3
"""Generate Loopflow screenshots for documentation.

Supports Concerto in-app snapshots and UI test screenshots.

Usage:
    python scripts/generate_screenshots.py
    python scripts/generate_screenshots.py --output docs/
    python scripts/generate_screenshots.py --manifest scripts/screenshots.yaml
    python scripts/generate_screenshots.py --snapshot-only
    python scripts/generate_screenshots.py --ui-test-only
    python scripts/generate_screenshots.py --repo-path ~/src/loopflow-demos --no-clone

Note: Concerto screenshots are generated by in-app snapshots and do not require
Screen Recording permission.
"""

import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal

import yaml


@dataclass
class Screenshot:
    name: str
    type: Literal["snapshot", "uitest"] = "snapshot"
    # Snapshot options (Concerto app)
    window_size: tuple[int, int] | None = None
    select_branch: str | None = None
    mock_loops: bool = False
    mock_config: str | None = None
    select_tab: str | None = None
    # Persona filtering
    directions: list[str] = field(default_factory=list)
    # UI test options
    ui_test_mode: str | None = None
    ui_test_select_branch: str | None = None
    ui_test_delay: float | None = None


@dataclass
class Manifest:
    repo_url: str
    local_path: Path
    screenshots: list[Screenshot] = field(default_factory=list)


def load_manifest(path: Path) -> Manifest:
    with open(path) as f:
        data = yaml.safe_load(f)

    screenshots = []
    for shot in data.get("screenshots", []):
        size = shot.get("window_size")
        screenshots.append(
            Screenshot(
                name=shot["name"],
                type=shot.get("type", "snapshot"),
                window_size=tuple(size) if size else None,
                select_branch=shot.get("select_branch"),
                mock_loops=shot.get("mock_loops", False),
                mock_config=shot.get("mock_config"),
                select_tab=shot.get("select_tab"),
                directions=shot.get("directions", []),
                ui_test_mode=shot.get("ui_test_mode"),
                ui_test_select_branch=shot.get("ui_test_select_branch"),
                ui_test_delay=shot.get("ui_test_delay"),
            )
        )

    local = data.get("local", "~/src/loopflow-demos")
    return Manifest(
        repo_url=data.get("repo", ""),
        local_path=Path(local).expanduser(),
        screenshots=screenshots,
    )


def _run_command(
    args: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    timeout: int | None = None,
    capture_output: bool = False,
    label: str,
    log_path: Path | None = None,
) -> subprocess.CompletedProcess:
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            env=env,
            check=True,
            capture_output=capture_output,
            text=capture_output,
            timeout=timeout,
        )
        _write_command_log(log_path, args, result, duration=None)
        return result
    except subprocess.TimeoutExpired as exc:
        _write_timeout_log(log_path, args, timeout)
        raise TimeoutError(f"{label} timed out after {timeout}s") from exc


def _write_command_log(
    log_path: Path | None,
    args: list[str],
    result: subprocess.CompletedProcess,
    duration: float | None,
) -> None:
    if not log_path:
        return
    log_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"time: {datetime.now().isoformat()}",
        f"args: {' '.join(args)}",
        f"returncode: {result.returncode}",
    ]
    if duration is not None:
        lines.append(f"duration_seconds: {duration:.2f}")
    if result.stdout:
        lines.append("stdout:")
        lines.append(result.stdout)
    if result.stderr:
        lines.append("stderr:")
        lines.append(result.stderr)
    log_path.write_text("\n".join(lines) + "\n")


def _write_timeout_log(log_path: Path | None, args: list[str], timeout: int | None) -> None:
    if not log_path:
        return
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text(
        "\n".join(
            [
                f"time: {datetime.now().isoformat()}",
                f"args: {' '.join(args)}",
                f"timeout_seconds: {timeout}",
                "result: timeout",
            ]
        )
        + "\n"
    )


def setup_demo_repo(
    manifest: Manifest,
    repo_path_override: Path | None,
    allow_clone: bool,
    clone_ssh: bool,
    clone_timeout: int,
    worktree_timeout: int,
) -> Path:
    """Clone or locate demo repo, ensure it has worktrees."""
    repo_path = repo_path_override or manifest.local_path
    git_env = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}

    if not repo_path.exists():
        if not allow_clone:
            raise FileNotFoundError(
                f"Demo repo not found: {repo_path}. Pass --repo-path or remove --no-clone."
            )
        if not manifest.repo_url:
            raise ValueError("Manifest repo URL is empty. Provide --repo-path.")

        if clone_ssh:
            clone_url = manifest.repo_url.replace("https://github.com/", "git@github.com:")
            if not clone_url.endswith(".git"):
                clone_url += ".git"
        else:
            clone_url = manifest.repo_url

        print(f"Cloning {clone_url} to {repo_path}...")
        _run_command(
            ["git", "clone", clone_url, str(repo_path)],
            env=git_env,
            timeout=clone_timeout,
            label="git clone",
            log_path=None,
        )

    existing_worktrees = _list_worktrees(repo_path)
    if len(existing_worktrees) <= 1:
        print("Creating demo worktrees...")
        _create_demo_worktrees(repo_path, git_env=git_env, timeout=worktree_timeout)

    return repo_path


def _list_worktrees(repo_path: Path) -> list[str]:
    result = subprocess.run(
        ["git", "worktree", "list", "--porcelain"],
        cwd=repo_path,
        capture_output=True,
        text=True,
    )
    worktrees = []
    for line in result.stdout.split("\n"):
        if line.startswith("worktree "):
            worktrees.append(line.split(" ", 1)[1])
    return worktrees


def _create_demo_worktrees(
    repo_path: Path,
    git_env: dict[str, str],
    timeout: int,
) -> None:
    branches = ["wave-auth-feature", "wave-api-refactor"]
    for branch in branches:
        worktree_path = repo_path.parent / f"{repo_path.name}.{branch}"
        if worktree_path.exists():
            continue
        _run_command(
            ["git", "worktree", "add", "-b", branch, str(worktree_path)],
            cwd=repo_path,
            env=git_env,
            timeout=timeout,
            label="git worktree add",
            log_path=None,
        )
        dummy_file = worktree_path / f"{branch}.txt"
        dummy_file.write_text(f"Demo file for {branch}\n")
        _run_command(
            ["git", "add", "."],
            cwd=worktree_path,
            env=git_env,
            timeout=timeout,
            label="git add",
            log_path=None,
        )
        _run_command(
            ["git", "commit", "-m", f"Add {branch} feature"],
            cwd=worktree_path,
            env=git_env,
            timeout=timeout,
            label="git commit",
            log_path=None,
        )


def find_concerto_executable(
    build_timeout: int,
    verbose: bool,
    log_dir: Path | None,
) -> Path:
    """Find the Concerto executable.

    Prefers app bundle executable for consistent assets and windowing.
    """
    derived_data = Path.home() / "Library/Developer/Xcode/DerivedData"
    install_path = Path("/Applications/Concerto.app")
    executable_path = install_path / "Contents/MacOS/Concerto"

    # Prefer app bundle for stable app resources and paths.
    # Check LoopflowSwift builds first, then Concerto and swift builds
    for pattern in ["LoopflowSwift-", "Concerto-", "swift-"]:
        for d in derived_data.iterdir():
            if d.name.startswith(pattern):
                # Prefer app bundle executable over bare binary
                for app_name in ["Concerto.app/Contents/MacOS/Concerto", "Concerto"]:
                    release = d / "Build/Products/Release" / app_name
                    debug = d / "Build/Products/Debug" / app_name
                    if release.exists():
                        if release.parts[-3] == "Concerto.app":
                            _install_app_bundle(release.parent.parent.parent, install_path)
                            _verify_executable_exists(executable_path)
                            return executable_path
                    if debug.exists():
                        if debug.parts[-3] == "Concerto.app":
                            _install_app_bundle(debug.parent.parent.parent, install_path)
                            _verify_executable_exists(executable_path)
                            return executable_path

    # Try building
    repo_root = Path(__file__).parent.parent
    swift_dir = repo_root / "swift"
    if swift_dir.exists():
        print("Generating Xcode project...")
        _run_command(
            ["xcodegen", "generate"],
            cwd=swift_dir,
            capture_output=not verbose,
            label="xcodegen generate",
        )
        print("Building Concerto...")
        build_args = [
            "xcodebuild",
            "-scheme",
            "Concerto",
            "-configuration",
            "Release",
            "-destination",
            "platform=macOS",
            "build",
        ]
        build_log = log_dir / "xcodebuild.log" if log_dir else None
        build_configs = [("Release", build_args), ("Debug", build_args.copy())]
        build_configs[1][1][build_configs[1][1].index("-configuration") + 1] = "Debug"
        build_success = False
        for name, args in build_configs:
            try:
                _run_command(
                    args,
                    cwd=swift_dir,
                    capture_output=not verbose,
                    timeout=build_timeout,
                    label=f"xcodebuild ({name})",
                    log_path=build_log if not verbose else None,
                )
                build_success = True
                break
            except Exception as exc:
                print(f"{name} build failed: {exc}")
        if not build_success:
            raise RuntimeError("Concerto build failed in both Release and Debug")
        # Check again - look for app bundle first
        for pattern in ["LoopflowSwift-", "swift-"]:
            for d in derived_data.iterdir():
                if d.name.startswith(pattern):
                    release = d / "Build/Products/Release/Concerto.app/Contents/MacOS/Concerto"
                    if release.exists():
                        _install_app_bundle(release.parent.parent.parent, install_path)
                        _verify_executable_exists(executable_path)
                        return executable_path
                    debug = d / "Build/Products/Debug/Concerto.app/Contents/MacOS/Concerto"
                    if debug.exists():
                        _install_app_bundle(debug.parent.parent.parent, install_path)
                        _verify_executable_exists(executable_path)
                        return executable_path

    raise FileNotFoundError(
        "Could not find Concerto. Build it first with: "
        "xcodebuild -scheme Concerto -configuration Release -destination 'platform=macOS' build"
    )


def _install_app_bundle(app_path: Path, install_path: Path) -> None:
    if not app_path.exists():
        raise FileNotFoundError(f"Concerto app not found at {app_path}")
    if app_path.suffix != ".app":
        raise ValueError(f"Expected app bundle at {app_path}")
    if install_path.exists():
        subprocess.run(
            ["rsync", "-a", "--delete", f"{app_path}/", f"{install_path}/"],
            check=True,
        )
    else:
        subprocess.run(["cp", "-R", str(app_path), str(install_path)], check=True)


def _verify_executable_exists(executable_path: Path) -> None:
    if not executable_path.exists():
        raise FileNotFoundError(
            f"Concerto executable not found at {executable_path}. "
            "Build the app with Xcode, then re-run the screenshot script."
        )


def snapshot_swift_screenshot(
    shot: Screenshot,
    repo_path: Path,
    output_dir: Path,
    executable: Path,
    snapshot_timeout: int,
    log_dir: Path | None,
) -> Path:
    """Launch Concerto with --snapshot, wait for output."""
    output_path = output_dir / f"{shot.name}.png"

    args = [
        str(executable),
        "--snapshot",
        str(output_path),
        "--repo",
        str(repo_path),
    ]

    if shot.window_size:
        args.extend(["--size", f"{shot.window_size[0]}x{shot.window_size[1]}"])

    if shot.select_branch:
        args.extend(["--select", shot.select_branch])

    if shot.mock_loops:
        args.append("--mock-loops")

    if shot.mock_config:
        args.extend(["--mock-config", shot.mock_config])

    if shot.select_tab:
        args.extend(["--tab", shot.select_tab])

    print(f"Snapshotting {shot.name} (Concerto)...")
    log_path = log_dir / f"{shot.name}.log" if log_dir else None
    start = datetime.now()
    try:
        result = subprocess.run(args, capture_output=True, text=True, timeout=snapshot_timeout)
        duration = (datetime.now() - start).total_seconds()
        _write_command_log(log_path, args, result, duration=duration)
        if result.returncode != 0 and result.stderr:
            print(f"  stderr: {result.stderr}")
    except subprocess.TimeoutExpired:
        _write_timeout_log(log_path, args, snapshot_timeout)
        print(f"  Error: snapshot timed out after {snapshot_timeout}s")

    if not output_path.exists():
        raise RuntimeError(f"Snapshot not created: {output_path}")

    print(f"  -> {output_path}")
    return output_path


def capture_ui_test_screenshot(
    shot: Screenshot,
    output_dir: Path,
    log_dir: Path | None,
    test_timeout: int,
) -> Path:
    output_path = output_dir / f"{shot.name}.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    swift_dir = Path(__file__).parent.parent / "swift"
    log_path = log_dir / f"{shot.name}.uitest.log" if log_dir else None

    env = os.environ.copy()
    env["CONCERTO_UI_TEST_NAME"] = shot.name
    if shot.ui_test_mode:
        env["CONCERTO_UI_TEST_MODE"] = shot.ui_test_mode
    if shot.ui_test_select_branch:
        env["CONCERTO_UI_TEST_SELECT_BRANCH"] = shot.ui_test_select_branch
    if shot.ui_test_delay is not None:
        env["CONCERTO_UI_TEST_DELAY"] = str(shot.ui_test_delay)

    args = [
        "xcodebuild",
        "-scheme",
        "Concerto",
        "-destination",
        "platform=macOS",
        "test",
        "-only-testing:ConcertoUITests/ScreenshotPipelineTests/testCapture",
    ]

    print(f"Capturing {shot.name} (UI test)...")
    start = datetime.now()
    try:
        result = subprocess.run(
            args,
            cwd=swift_dir,
            env=env,
            capture_output=True,
            text=True,
            timeout=test_timeout,
        )
        duration = (datetime.now() - start).total_seconds()
        _write_command_log(log_path, args, result, duration=duration)
        stdout = result.stdout.strip()
        stderr = result.stderr.strip()
        if result.returncode != 0 and stderr:
            print(f"  stderr: {stderr}")
    except subprocess.TimeoutExpired:
        _write_timeout_log(log_path, args, test_timeout)
        print(f"  Error: UI test timed out after {test_timeout}s")

    temp_path = None
    if "stdout" in locals() and stdout:
        for line in stdout.splitlines():
            if line.startswith("UI_TEST_SCREENSHOT_PATH="):
                temp_path = line.split("=", 1)[1].strip()
                break

    if temp_path and Path(temp_path).exists():
        shutil.copy(Path(temp_path), output_path)
    else:
        raise RuntimeError(f"UI test screenshot not created: {output_path}")

    print(f"  -> {output_path}")
    return output_path


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate Loopflow screenshots")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("docs/screenshots"),
        help="Output directory for screenshots",
    )
    parser.add_argument(
        "--manifest",
        "-m",
        type=Path,
        default=Path("scripts/screenshots.yaml"),
        help="Path to manifest file",
    )
    parser.add_argument(
        "--snapshot-only",
        action="store_true",
        help="Only capture Concerto snapshot screenshots",
    )
    parser.add_argument(
        "--ui-test-only",
        action="store_true",
        help="Only capture Concerto UI test screenshots",
    )
    parser.add_argument(
        "--repo-path",
        type=Path,
        help="Override demo repo path for Concerto snapshots",
    )
    parser.add_argument(
        "--no-clone",
        action="store_true",
        help="Fail if demo repo is missing instead of cloning",
    )
    parser.add_argument(
        "--clone-ssh",
        action="store_true",
        help="Clone demo repo over SSH instead of HTTPS",
    )
    parser.add_argument(
        "--clone-timeout",
        type=int,
        default=60,
        help="Timeout (seconds) for git clone",
    )
    parser.add_argument(
        "--worktree-timeout",
        type=int,
        default=30,
        help="Timeout (seconds) for demo worktree setup",
    )
    parser.add_argument(
        "--build-timeout",
        type=int,
        default=600,
        help="Timeout (seconds) for xcodebuild",
    )
    parser.add_argument(
        "--snapshot-timeout",
        type=int,
        default=30,
        help="Timeout (seconds) per Concerto snapshot",
    )
    parser.add_argument(
        "--ui-test-timeout",
        type=int,
        default=120,
        help="Timeout (seconds) per UI test screenshot",
    )
    parser.add_argument(
        "--direction",
        "-d",
        help="Only generate screenshots tagged with this direction (e.g. conductor)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Stream xcodebuild output",
    )
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=Path("scratch/screenshot-logs"),
        help="Directory for screenshot capture logs",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    manifest_path = repo_root / args.manifest
    output_dir = repo_root / args.output

    if not manifest_path.exists():
        print(f"Manifest not found: {manifest_path}")
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest(manifest_path)

    # Filter screenshots by type
    screenshots = manifest.screenshots
    if args.snapshot_only:
        screenshots = [s for s in screenshots if s.type == "snapshot"]
    elif args.ui_test_only:
        screenshots = [s for s in screenshots if s.type == "uitest"]

    # Filter by direction
    if args.direction:
        screenshots = [s for s in screenshots if args.direction in s.directions]

    # Setup for Concerto snapshots
    snapshot_screenshots = [s for s in screenshots if s.type == "snapshot"]
    ui_test_screenshots = [s for s in screenshots if s.type == "uitest"]

    executable = None
    repo_path = None

    log_dir = None if args.log_dir is None else (repo_root / args.log_dir)

    if snapshot_screenshots:
        executable = find_concerto_executable(
            args.build_timeout,
            args.verbose,
            log_dir,
        )
        repo_path = setup_demo_repo(
            manifest=manifest,
            repo_path_override=args.repo_path,
            allow_clone=not args.no_clone,
            clone_ssh=args.clone_ssh,
            clone_timeout=args.clone_timeout,
            worktree_timeout=args.worktree_timeout,
        )
        print(f"Using Concerto: {executable}")
        print(f"Using repo: {repo_path}")

        print(f"Output: {output_dir}")
        print()

    if ui_test_screenshots:
        _run_command(
            ["xcodegen", "generate"],
            cwd=repo_root / "swift",
            capture_output=not args.verbose,
            label="xcodegen generate",
            log_path=log_dir / "xcodegen.log" if log_dir else None,
        )

    captured = 0
    for shot in screenshots:
        try:
            if shot.type == "snapshot" and executable and repo_path:
                snapshot_swift_screenshot(
                    shot,
                    repo_path,
                    output_dir,
                    executable,
                    args.snapshot_timeout,
                    log_dir,
                )
                captured += 1
            elif shot.type == "uitest":
                capture_ui_test_screenshot(
                    shot,
                    output_dir,
                    log_dir,
                    args.ui_test_timeout,
                )
                captured += 1
        except Exception as e:
            print(f"  Error: {e}")

    print()
    print(f"Done! {captured}/{len(screenshots)} screenshots generated.")


if __name__ == "__main__":
    main()
