"""Tests for the shell installer generated by .github/workflows/release.yml.

The installer is a heredoc inside the release workflow. These tests extract it
and exercise its argument parsing and download error handling with stub
curl/tar binaries so no network is touched.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
RELEASE_YML = REPO_ROOT / ".github" / "workflows" / "release.yml"


def _extract_installer() -> str:
    lines = RELEASE_YML.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if "<< 'INSTALLER'" in line)
    indent = len(lines[start]) - len(lines[start].lstrip())
    body: list[str] = []
    for line in lines[start + 1 :]:
        dedented = line[indent:]
        if dedented.rstrip() == "INSTALLER":
            return "\n".join(body) + "\n"
        body.append(dedented)
    raise AssertionError("INSTALLER heredoc not terminated in release.yml")


def _write_stubs(stub_dir: Path) -> None:
    """Stub curl (logs args, fakes the download) and tar (drops lf/lfd)."""
    stub_dir.mkdir(parents=True, exist_ok=True)
    curl = stub_dir / "curl"
    curl.write_text(
        "#!/bin/sh\n"
        'out=""; prev=""\n'
        'for a in "$@"; do [ "$prev" = "-o" ] && out="$a"; prev="$a"; done\n'
        'echo "$@" >> "$LFTEST_LOG"\n'
        '[ -n "$out" ] && echo dummy > "$out"\n'
        "exit ${LFTEST_CURL_RC:-0}\n"
    )
    tar = stub_dir / "tar"
    tar.write_text(
        "#!/bin/sh\n"
        'dir=""; prev=""\n'
        'for a in "$@"; do [ "$prev" = "-C" ] && dir="$a"; prev="$a"; done\n'
        '[ -n "$dir" ] && { echo x > "$dir/lf"; echo x > "$dir/lfd"; }\n'
        "exit 0\n"
    )
    for f in (curl, tar):
        f.chmod(0o755)


def _run(script: Path, args: list[str], env_extra: dict[str, str]) -> subprocess.CompletedProcess:
    env = {**os.environ, **env_extra}
    return subprocess.run(
        ["sh", str(script), *args],
        capture_output=True,
        text=True,
        env=env,
    )


@pytest.fixture
def installer(tmp_path: Path) -> Path:
    script = tmp_path / "install.sh"
    script.write_text(_extract_installer())
    return script


@pytest.fixture
def env(tmp_path: Path) -> dict[str, str]:
    stub_dir = tmp_path / "stub"
    _write_stubs(stub_dir)
    return {
        "PATH": f"{stub_dir}:{os.environ['PATH']}",
        "LF_INSTALL_DIR": str(tmp_path / "dest"),
        "LFTEST_LOG": str(tmp_path / "curl.log"),
    }


def test_installer_syntax_is_valid(installer: Path) -> None:
    """A malformed heredoc would ship a broken installer to every user."""
    result = subprocess.run(["sh", "-n", str(installer)], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_no_interactive_is_not_read_as_version(
    installer: Path, env: dict[str, str], tmp_path: Path
) -> None:
    """Regression: `--no-interactive` once became `v--no-interactive` -> 404."""
    result = _run(installer, ["--no-interactive"], env)
    assert result.returncode == 0, result.stderr
    log = (tmp_path / "curl.log").read_text()
    assert "v--no-interactive" not in log
    assert "releases/latest/download" in log


def test_positional_version_builds_versioned_url(
    installer: Path, env: dict[str, str], tmp_path: Path
) -> None:
    result = _run(installer, ["0.9.9"], env)
    assert result.returncode == 0, result.stderr
    assert "download/v0.9.9/" in (tmp_path / "curl.log").read_text()


def test_explicit_version_builds_versioned_url(
    installer: Path, env: dict[str, str], tmp_path: Path
) -> None:
    result = _run(installer, ["--version", "0.9.9"], env)
    assert result.returncode == 0, result.stderr
    assert "download/v0.9.9/" in (tmp_path / "curl.log").read_text()


def test_equals_version_builds_versioned_url(
    installer: Path, env: dict[str, str], tmp_path: Path
) -> None:
    result = _run(installer, ["--version=0.9.9"], env)
    assert result.returncode == 0, result.stderr
    assert "download/v0.9.9/" in (tmp_path / "curl.log").read_text()


def test_missing_version_value_fails_clearly(installer: Path, env: dict[str, str]) -> None:
    result = _run(installer, ["--version"], env)
    assert result.returncode != 0
    assert "--version requires a value" in result.stderr
    assert "Usage:" in result.stderr


def test_unknown_flag_fails_clearly(installer: Path, env: dict[str, str]) -> None:
    result = _run(installer, ["--bogus"], env)
    assert result.returncode != 0
    assert "Unknown option" in result.stderr
    assert "Usage:" in result.stderr


def test_download_failure_aborts_without_cryptic_error(installer: Path, tmp_path: Path) -> None:
    """A failed download must abort loudly, not leak a confusing `cp` error."""
    stub_dir = tmp_path / "stub"
    _write_stubs(stub_dir)
    env_extra = {
        "PATH": f"{stub_dir}:{os.environ['PATH']}",
        "LF_INSTALL_DIR": str(tmp_path / "dest"),
        "LFTEST_LOG": str(tmp_path / "curl.log"),
        "LFTEST_CURL_RC": "22",
    }
    result = _run(installer, [], env_extra)
    assert result.returncode != 0
    assert "Download failed" in result.stderr
    assert "No such file" not in (result.stdout + result.stderr)
