ALTER TABLE tasks ADD COLUMN automation_enabled INTEGER CHECK (automation_enabled IN (0,1));
ALTER TABLE tasks ADD COLUMN automation_exec_id TEXT REFERENCES execs(id);
ALTER TABLE tasks ADD COLUMN automation_retry_key TEXT;
ALTER TABLE tasks ADD COLUMN automation_retries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN automation_checked_at INTEGER;
ALTER TABLE tasks ADD COLUMN automation_detail TEXT;
ALTER TABLE ci_incidents ADD COLUMN repair_exec_id TEXT REFERENCES execs(id);
ALTER TABLE ci_incidents ADD COLUMN repair_session_id TEXT REFERENCES agent_sessions(id);
ALTER TABLE ci_incidents ADD COLUMN repair_retries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ci_incidents ADD COLUMN repair_finished_at INTEGER;
ALTER TABLE ci_incidents ADD COLUMN repair_error TEXT;
ALTER TABLE pr_landings ADD COLUMN ci_pending_head TEXT;
ALTER TABLE pr_landings ADD COLUMN ci_pending_since INTEGER;
ALTER TABLE pr_landings ADD COLUMN ci_timeout_reruns INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pr_landings ADD COLUMN ci_pending_attempt TEXT;
ALTER TABLE ci_incidents ADD COLUMN repair_conclusion TEXT CHECK (repair_conclusion IN ('published','blocked'));
